packages:
  - 'api-gateway'
  - 'microservices/*'
  - 'frontend/apps/*'
  - 'frontend/packages/*'
allowBuilds:
  '@scarf/scarf': true
  argon2: true
  bcrypt: true
  cpu-features: set this to true or false
  sharp: set this to true or false
  sqlite3: true
  ssh2: set this to true or false
  unrs-resolver: set this to true or false
