groups:
  - name: API_Alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High HTTP 5xx error rate detected"
          description: "Gateway error rate is > 5 per second for over 2 minutes."
          
      - alert: HighLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1.0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High API Latency"
          description: "P95 latency is > 1s for over 2 minutes."
